apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dgozalo
    provider: github
    repository: gotest-cluster-4-cjxd1
  name: dgozalo-gotest-cluster-4-cjxd1
spec:
  description: Imported application for dgozalo/gotest-cluster-4-cjxd1
  httpCloneURL: https://github.com/dgozalo/gotest-cluster-4-cjxd1.git
  org: dgozalo
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: gotest-cluster-4-cjxd1
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dgozalo/gotest-cluster-4-cjxd1.git
