adminUser:
  password: vault:test-cluster-4/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dgozalo@cloudbees.com
  token: vault:test-cluster-4/pipelineUser:token
  username: dgozalo
prow:
  hmacToken: vault:test-cluster-4/prow:hmacToken
